import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ConfirmDialog } from '../components/Modal.jsx'
import { deleteAllLocalData, exportAllProjectsSnapshot, readSettings, replaceAllProjects, writeSettings } from '../database/repositories.js'
import { DATABASE_SCHEMA_VERSION, JSON_BACKUP_LIMIT } from '../domain/constants.js'
import { APP_VERSION } from '../app/version.js'
import { APP_FONT_FAMILIES, createAppSettings } from '../domain/normalization.js'
import { migrateAppSettings, migrateBackup } from '../database/migrations.js'
import { validateAllProjectsBackup } from '../domain/validation.js'
import { useUiStore, notify } from '../stores/uiStore.js'
import { useWorkspaceStore } from '../stores/workspaceStore.js'
import { createAsyncWriteQueue } from '../domain/asyncWriteQueue.js'
import { serializeBackupWithinLimit } from '../domain/backupSerialization.js'

const fontChoices = [
  { value: 'inter', label: 'Inter', css: '"Inter Variable", Inter, sans-serif', description: 'Clean and compact' },
  { value: 'manrope', label: 'Manrope', css: '"Manrope Variable", Manrope, sans-serif', description: 'Modern and open' },
  { value: 'source-sans-3', label: 'Source Sans 3', css: '"Source Sans 3 Variable", "Source Sans 3", sans-serif', description: 'Clear for tables' },
  { value: 'atkinson-hyperlegible', label: 'Atkinson Hyperlegible', css: '"Atkinson Hyperlegible", sans-serif', description: 'Distinct characters' },
].filter((font) => APP_FONT_FAMILIES.includes(font.value))

export function SettingsPage() {
  const navigate=useNavigate(); const inputRef=useRef(null); const settingsRef=useRef(null); const settingsWriteQueue=useRef(createAsyncWriteQueue()); const settingsWriteRevision=useRef(0); const failedSettingsWrite=useRef(null); const [settings,setSettings]=useState(null); const [error,setError]=useState(''); const [restore,setRestore]=useState(null); const [deleteStep,setDeleteStep]=useState(0); const [working,setWorking]=useState(false)
  const project=useWorkspaceStore((state)=>state.project); const setPreferences=useUiStore((state)=>state.setPreferences)
  useEffect(()=>{let live=true;readSettings().then((value)=>{if(live){settingsRef.current=value;setSettings(value);setPreferences(value)}}).catch((reason)=>{if(live)setError(reason.message)});return()=>{live=false}},[setPreferences])
  const update=(key,value)=>{const current=settingsRef.current;if(!current)return;const revision=++settingsWriteRevision.current;const next={...current,[key]:value};settingsRef.current=next;setSettings(next);setPreferences(next);const pending=settingsWriteQueue.current.enqueue(async()=>{try{await writeSettings(next);failedSettingsWrite.current=null;window.dispatchEvent(new Event('boq-settings-updated'))}catch(reason){failedSettingsWrite.current=reason;try{const persisted=await readSettings();if(revision===settingsWriteRevision.current){settingsRef.current=persisted;setSettings(persisted);setPreferences(persisted)}}catch{/* Keep the original write failure as the actionable error. */}throw reason}});pending.catch((reason)=>notify(`Could not save preference: ${reason.message}`,'error'));return pending}
  const exportBackup=async()=>{setWorking(true);try{await settingsWriteQueue.current.idle();if(failedSettingsWrite.current)throw new Error(`A preference change could not be saved: ${failedSettingsWrite.current.message}`);const snapshot=await exportAllProjectsSnapshot();const backup={backupType:'boq-cost-load-all-projects',schemaVersion:1,exportedAt:new Date().toISOString(),...snapshot};const json=serializeBackupWithinLimit(backup,JSON_BACKUP_LIMIT);const url=URL.createObjectURL(new Blob([json],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`boq-cost-load-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Full workspace backup downloaded.')}catch(reason){notify(`Backup export failed: ${reason.message}`,'error')}finally{setWorking(false)}}
   const chooseRestore=async(event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>JSON_BACKUP_LIMIT){notify(`Backup must be ${Math.floor(JSON_BACKUP_LIMIT/1024/1024)} MB or smaller.`,'error');return}setWorking(true);try{const parsed=JSON.parse(await file.text());const migrated=migrateBackup(parsed);if(migrated.backupType!=='boq-cost-load-all-projects')throw new Error('Choose a full workspace backup exported from Settings.');const backup={...migrated,settings:migrateAppSettings(migrated.settings)};const errors=validateAllProjectsBackup(backup);if(errors.length)throw new Error(errors[0]);setRestore({backup,fileName:file.name})}catch(reason){notify(`Backup could not be opened: ${reason.message}`,'error')}finally{setWorking(false)}}
  const confirmRestore=async()=>{if(!restore)return;setWorking(true);try{await settingsWriteQueue.current.idle();await useWorkspaceStore.getState().guardNavigation();await replaceAllProjects(restore.backup);useWorkspaceStore.getState().clear();settingsRef.current=restore.backup.settings;setPreferences(restore.backup.settings);setSettings(restore.backup.settings);failedSettingsWrite.current=null;setRestore(null);window.dispatchEvent(new Event('boq-settings-updated'));notify('Workspace restored.');navigate('/projects')}catch(reason){notify(`Restore failed: ${reason.message}`,'error')}finally{setWorking(false)}}
  const confirmDelete=async()=>{setWorking(true);try{await settingsWriteQueue.current.idle();await useWorkspaceStore.getState().guardNavigation();await deleteAllLocalData();useWorkspaceStore.getState().clear();const defaults=createAppSettings();settingsRef.current=defaults;setSettings(defaults);setPreferences(defaults);failedSettingsWrite.current=null;setDeleteStep(0);window.dispatchEvent(new Event('boq-settings-updated'));notify('All local application data was deleted.');navigate('/projects')}catch(reason){notify(`Could not delete local data: ${reason.message}`,'error')}finally{setWorking(false)}}
  if(error)return <div className="page-wrap"><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><div className="placeholder-panel" role="alert">Could not load settings: {error} <button className="secondary-button" onClick={()=>window.location.reload()}>Reload</button></div></div>
  if(!settings)return <div className="page-wrap"><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><div className="placeholder-panel" role="status">Loading preferences…</div></div>
  return <div className="page-wrap settings-page">
    <p className="eyebrow">PREFERENCES</p><h1>Settings</h1><p className="subtitle">Personalize the workspace, choose defaults for new estimates, and protect your local data.</p>
     <SettingsSection title="Appearance" description="Choose how the workspace looks. Font and text size apply throughout the app; worksheet density changes row height.">
        <SettingRow label="App theme" help="Light, Warm light, and Dark override each project's saved theme. Follow system uses the device theme unless the open project has its own dark mode enabled. New projects use the project theme default below."><select value={settings.theme} onChange={(e)=>update('theme',e.target.value)}><option value="system">Follow system</option><option value="light">Light</option><option value="warm">Warm light</option><option value="dark">Dark</option></select></SettingRow>
       <div className="setting-font-row"><div><strong>Font family</strong><small>Choose a clear, modern font for the whole app. The selection is saved on this device.</small></div><div className="settings-font-grid" role="radiogroup" aria-label="Application font family">{fontChoices.map((font)=><label className={`settings-font-choice${settings.fontFamily===font.value?' is-selected':''}`} key={font.value}><input type="radio" name="app-font-family" value={font.value} checked={settings.fontFamily===font.value} onChange={()=>update('fontFamily',font.value)}/><span className="settings-font-choice-content"><strong>{font.label}</strong><small>{font.description}</small><span className="settings-font-preview" style={{fontFamily:font.css}}>Aa 0123 · BOQ estimate</span><span className="settings-font-glyph-preview" style={{fontFamily:font.css}}>1 I l · 0 O · $ 123.45</span></span></label>)}</div></div>
       <SettingRow label="Text size" help="Adjusts interface and worksheet text."><select value={settings.fontSize} onChange={(e)=>update('fontSize',e.target.value)}><option value="small">Small</option><option value="default">Default</option><option value="large">Large</option></select></SettingRow>
      <SettingRow label="Worksheet density" help="Changes grid row height; existing cell values are unaffected."><select value={settings.density} onChange={(e)=>update('density',e.target.value)}><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></SettingRow>
    </SettingsSection>
    <SettingsSection title="Project defaults" description="These choices are applied when creating new projects or sheets; existing ones keep their individual settings.">
      <SettingRow label="Dark mode for new projects" help="Each project can still be changed independently."><input type="checkbox" checked={settings.defaultDarkMode} onChange={(e)=>update('defaultDarkMode',e.target.checked)}/></SettingRow>
      <SettingRow label="Show Remark on new sheets" help="Existing sheets retain their current column visibility."><input type="checkbox" checked={settings.defaultRemarkVisible} onChange={(e)=>update('defaultRemarkVisible',e.target.checked)}/></SettingRow>
      {project&&<SettingRow label={`Dark mode for ${project.name}`} help={settings.theme==='dark'||settings.theme==='warm'?'Saved project choice; overridden by the selected app theme.':'Changes the currently open project only.'}><input type="checkbox" checked={project.darkMode} onChange={async(e)=>{try{const next={...project,darkMode:e.target.checked};const {saveProjectMetadata}=await import('../database/repositories.js');const saved=await saveProjectMetadata(next);useWorkspaceStore.getState().syncProject(saved)}catch(reason){notify(`Could not update project theme: ${reason.message}`,'error')}}}/></SettingRow>}
    </SettingsSection>
    <SettingsSection title="Number display" description="Formatting affects display only. Stored values, calculations, filtering, and exports keep their full precision.">
      <SettingRow label="Quantity decimal places"><select value={settings.quantityDecimals} onChange={(e)=>update('quantityDecimals',Number(e.target.value))}>{[0,1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></SettingRow>
      <SettingRow label="Cost decimal places"><select value={settings.costDecimals} onChange={(e)=>update('costDecimals',Number(e.target.value))}>{[0,1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></SettingRow>
      <SettingRow label="Thousands separators"><input type="checkbox" checked={settings.useGrouping} onChange={(e)=>update('useGrouping',e.target.checked)}/></SettingRow>
      <SettingRow label="Currency label" help="Optional display label, such as USD, EUR, or $. It does not convert values."><input className="setting-text-input" maxLength="12" value={settings.currencyLabel} placeholder="None" onChange={(e)=>update('currencyLabel',e.target.value)}/></SettingRow>
    </SettingsSection>
    <SettingsSection title="Data & backups" description="Estimates are saved in this browser profile using local browser storage. Back up regularly to move or protect your work.">
      <div className="settings-backup-actions"><button className="primary-button" type="button" disabled={working} onClick={exportBackup}>Export all projects</button><button className="secondary-button" type="button" disabled={working} onClick={()=>inputRef.current?.click()}>Restore workspace backup</button><input ref={inputRef} className="visually-hidden" type="file" accept="application/json,.json" onChange={chooseRestore}/></div>
      <SettingRow label="Show browser storage reminder" help="The reminder includes a note to keep JSON backups."><input type="checkbox" checked={!settings.storageNoticeDismissed} onChange={(e)=>update('storageNoticeDismissed',!e.target.checked)}/></SettingRow>
    </SettingsSection>
    <SettingsSection title="Application information" description="Version and local data maintenance."><div className="setting-row"><div><strong>Application version</strong></div><span>{APP_VERSION}</span></div><div className="setting-row"><div><strong>Database schema version</strong></div><span>{DATABASE_SCHEMA_VERSION}</span></div><div className="settings-backup-actions"><button className="danger-button" type="button" disabled={working} onClick={()=>setDeleteStep(1)}>Delete all local application data</button></div></SettingsSection>
    <SettingsSection title="Quick help" description="Useful shortcuts and cost definitions for the worksheet."><div className="settings-help-grid"><p><kbd>Ctrl + Z</kbd> Undo · <kbd>Ctrl + Y</kbd> Redo</p><p><kbd>Ctrl + F</kbd> Find · <kbd>Ctrl + H</kbd> Find and replace</p><p><kbd>Ctrl + Shift + D</kbd> Toggle project dark mode · <kbd>Ctrl + S</kbd> Save</p><p><strong>Cost</strong> = CQBI × CR × Rate</p><p><strong>Used Cost</strong> = Override when entered, otherwise Cost</p><p><strong>Total Cost</strong> = Used Cost × BOQ Qty</p></div></SettingsSection>
    {restore&&<ConfirmDialog title="Replace all workspace data?" danger confirmLabel={working?'Restoring…':'Replace workspace'} onClose={()=>setRestore(null)} onConfirm={confirmRestore}><p><strong>{restore.fileName}</strong> contains {restore.backup.projects.length} project(s), {restore.backup.sheets.length} sheet(s), and {`${restore.backup.assemblies?.length ?? 0} ${restore.backup.assemblies?.length === 1 ? 'assembly' : 'assemblies'}`}.</p><p>This replaces all projects, assemblies, and preferences saved in this browser. Export a backup first if you may need the current data.</p></ConfirmDialog>}
    {deleteStep===1&&<ConfirmDialog title="Delete all local data?" danger confirmLabel="Continue" onClose={()=>setDeleteStep(0)} onConfirm={()=>setDeleteStep(2)}><p>This will permanently remove every project, sheet, and application preference stored by this app in this browser.</p></ConfirmDialog>}
    {deleteStep===2&&<ConfirmDialog title="Confirm permanent deletion" danger confirmLabel={working?'Deleting…':'Delete everything'} onClose={()=>setDeleteStep(0)} onConfirm={confirmDelete}><p>This is the final confirmation. This action cannot be undone. Export a backup before continuing if you may need this data.</p></ConfirmDialog>}
  </div>
}

function SettingsSection({title,description,children}){return <section className="settings-section"><header><h2>{title}</h2><p>{description}</p></header><div>{children}</div></section>}
function SettingRow({label,help,children}){return <div className="setting-row"><div><strong>{label}</strong>{help&&<small>{help}</small>}</div>{children}</div>}
